### ISSUE TITLE
Collaborator data transfer question using PC rather than unix/mac OS

### ISSUE THREAD

**Issue by yingliu3** [Gibbons-Lab/wiki#1]
Dear ISB, 
As a UW collaborator our team recently uploaded our data to your S3 bucket successfully based on the instructions shown on the Collaborator data transfer tab. The question I have is that our data are stored in our lab's shared folder. However all of office desktops are all Windows PC. I have a personal MAC and I finally copy all our data needed to be uploaded to my MAC and then complete the whole uploading following the steps. 
When my colleagues and I tried to complete these steps using either command prompt or powershell using our office PCs, we always ran into issues. For example, after I thought I have done every step correctly (since I have completed the uploading using MAC myself, so I think I know what I was doing, although I am not a scripting savvy), I got the message of "The config profile (gibbons_collab) could not be found". I got confused. I ask this question because we might want to analyze more data through ISB and might need to upload more data, but we definite do not want to move data from our shared drive to my personal computer every time. I personally know that we should be able to conduct these tasks in PC as well, but I just could not figure it out. Thanks very much! 

PS C:\Users\MYUWID> dir .aws

    Directory: C:\Users\MYUWID\.aws

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         3/28/2023  12:36 PM            143 credentials.txt

PS C:\Users\yingliu3> Get-Content .\.aws\credentials.txt
[gibbons_collab]
region = us-east-2
aws_access_key_id = XXXXXXXXXXXXXXXXXXXXXX (the credential info we received)
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXX  (the credential info we received)

PS C:\Users\MYUWID> aws s3 --profile gibbons_collab ls s3://gibbons-sequencing

The config profile (gibbons_collab) could not be found

**Comment by cdiener** [comment]
Sorry for that. Never really tried on Windows. I suspect the configuration directory might be in a slightly different location. You can check with `aws configure list` where the last line indicates the directory used for the config. For instance for me:

```bash
(base) cdiener@moneta [teaching] aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
   [...]
   region                us-east-2      config-file    ~/.aws/config  <- check this one
```

Also, make sure the credentials file is only named `credentials` (without `.txt` or any other file ending). 

Let me know if any of that works, otherwise happy to investigate further.

Best

**Comment by yingliu3** [comment]
Yes! I tried the change name of the .txt file by removing the extension and it works now! Many thanks!

**Comment by cdiener** [comment]
Awesome, great to hear that!

**Comment by yingliu3** [comment]
C:\Users\yingliu3>aws s3 --profile gibbons_collab ls s3://gibbons-sequencing
                           PRE ........... our groups' uploaded data folder
                           PRE hpop/
                           PRE metaphlan4/
2020-03-05 12:15:35         12 if_you_see_this_it_worked
2022-11-21 14:36:14         32 mpa_latest
2022-11-21 14:36:16         70 mpa_vJan21_CHOCOPhlAnSGB_202103.md5

C:\Users\yingliu3>aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key                <not set>             None    None
secret_key                <not set>             None    None
    region                <not set>             None    None

Why there is nothing on the list? After I rename the credentials file name.
